# 拡張機能 Rest Client の利用
# REST APIのリクエストを送信するためのツール
# 
# 使い方
# 1. 拡張機能 Rest Client(humao.rest-client) をインストール
# 2. 下記の各リクエストの上に表示される Send Request を押すとリクエストが送信される
# 
# 参考
# https://github.com/Huachao/vscode-restclient

###
GET http://localhost:8080/api
